export type WidgetType =
  | "dday" | "life-calendar" | "time-progress" | "clock" | "quote"
  | "pomodoro" | "mini-calendar" | "analog-clock" | "counter" | "weather"
  | "reading" | "habit" | "timeline" | "banner"
  | "bookmark" | "goal" | "stopwatch" | "music";

export interface TemplateWidget {
  type: WidgetType;
  name: string;
  url: string;
  editorUrl: string;
  previewProps: Record<string, unknown>;
}

export interface Template {
  id: string;
  title: string;
  desc: string;
  layout: number[][];
  widgets: TemplateWidget[];
}

export interface LayoutPreset {
  id: string;
  name: string;
  desc: string;
  slots: number;
  grid: number[][];
}

export const layoutPresets: LayoutPreset[] = [
  { id: "single", name: "1열 스택", desc: "세로 나열", slots: 3, grid: [[1], [1], [1]] },
  { id: "two-col", name: "2열 균등", desc: "나란히 2개", slots: 2, grid: [[1, 1]] },
  { id: "three-col", name: "3열 균등", desc: "나란히 3개", slots: 3, grid: [[1, 1, 1]] },
  { id: "header-two", name: "헤더 + 2열", desc: "전폭 헤더 아래 2열", slots: 3, grid: [[1], [1, 1]] },
  { id: "two-footer", name: "2열 + 전폭", desc: "2열 아래 전폭 푸터", slots: 3, grid: [[1, 1], [1]] },
  { id: "grid-2x2", name: "2×2 그리드", desc: "정사각 그리드", slots: 4, grid: [[1, 1], [1, 1]] },
  { id: "header-three", name: "헤더 + 3열", desc: "전폭 + 3열", slots: 4, grid: [[1], [1, 1, 1]] },
  { id: "sandwich", name: "샌드위치", desc: "전폭+2열+전폭", slots: 4, grid: [[1], [1, 1], [1]] },
  { id: "dashboard", name: "대시보드", desc: "2+2+1", slots: 5, grid: [[1, 1], [1, 1], [1]] },
];

export interface WidgetDefault {
  type: WidgetType;
  name: string;
  defaultUrl: string;
}

export const widgetDefaults: WidgetDefault[] = [
  { type: "dday", name: "D-Day 위젯", defaultUrl: "/widget/dday?title=D-Day&date=2026-12-31&bg=1E1E1E&text=FFFFFF" },
  { type: "clock", name: "미니멀 시계", defaultUrl: "/widget/clock?timezone=Asia/Seoul&format=24h&font=mono" },
  { type: "analog-clock", name: "아날로그 시계", defaultUrl: "/widget/analog-clock?timezone=Asia/Seoul" },
  { type: "mini-calendar", name: "미니 캘린더", defaultUrl: "/widget/mini-calendar?weekStart=mon&lang=ko" },
  { type: "timeline", name: "타임라인", defaultUrl: "/widget/timeline?events=일정1~2026-06-01|일정2~2026-09-01&color=2563EB" },
  { type: "time-progress", name: "시간 진행률 바", defaultUrl: "/widget/time-progress?type=year&color=2563EB" },
  { type: "life-calendar", name: "인생 달력", defaultUrl: "/widget/life-calendar?birthdate=2000-01-01&lifespan=80&color=22C55E" },
  { type: "reading", name: "읽기 진행률", defaultUrl: "/widget/reading?title=책+제목&current=50&total=300&color=2563EB" },
  { type: "goal", name: "목표 진행률", defaultUrl: "/widget/goal?title=목표&current=30&target=100&color=22C55E" },
  { type: "pomodoro", name: "뽀모도로 타이머", defaultUrl: "/widget/pomodoro?work=25&break=5&color=E11D48" },
  { type: "stopwatch", name: "스톱워치", defaultUrl: "/widget/stopwatch?btnColor=2563EB" },
  { type: "counter", name: "카운터", defaultUrl: "/widget/counter?label=카운터&initial=0&step=1&btnColor=2563EB" },
  { type: "habit", name: "습관 트래커", defaultUrl: "/widget/habit?title=습관&view=week&color=22C55E" },
  { type: "quote", name: "명언 카드", defaultUrl: "/widget/quote?text=오늘도+화이팅&author=작자미상&font=serif" },
  { type: "banner", name: "텍스트 배너", defaultUrl: "/widget/banner?texts=텍스트를+입력하세요&bold=true" },
  { type: "bookmark", name: "북마크", defaultUrl: "/widget/bookmark?url=https://example.com&title=북마크&desc=설명" },
  { type: "music", name: "음악 플레이어", defaultUrl: "/widget/music?title=Song&artist=Artist&artColor=6366F1" },
  { type: "weather", name: "날씨", defaultUrl: "/widget/weather?lat=37.5665&lon=126.978&city=서울" },
];

export const templates: Template[] = [
  {
    id: "student",
    title: "학생 대시보드",
    desc: "수능/시험 D-Day + 공부 타이머 + 진행률 관리를 한 곳에",
    layout: [[0, 4], [1, 2], [3, 5]],
    widgets: [
      {
        type: "dday",
        name: "수능 D-Day",
        url: "/widget/dday?title=%EC%88%98%EB%8A%A5&date=2026-11-19&bg=1E1E1E&text=FFFFFF",
        editorUrl: "/create/dday",
        previewProps: {
          title: "수능",
          targetDate: "2026-11-19",
          bgColor: "1E1E1E",
          textColor: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "pomodoro",
        name: "뽀모도로 타이머",
        url: "/widget/pomodoro?work=25&break=5&color=E11D48",
        editorUrl: "/create/pomodoro",
        previewProps: {
          workTime: 25,
          breakTime: 5,
          color: "E11D48",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "time-progress",
        name: "올해 진행률",
        url: "/widget/time-progress?type=year&color=2563EB",
        editorUrl: "/create/time-progress",
        previewProps: {
          type: "year",
          color: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "habit",
        name: "공부 습관 트래커",
        url: "/widget/habit?title=%EA%B3%B5%EB%B6%80&view=week&weekStart=mon&color=22C55E",
        editorUrl: "/create/habit",
        previewProps: {
          title: "공부",
          view: "week",
          weekStart: "mon",
          checkedDates: new Set(["2026-02-23", "2026-02-24", "2026-02-26"]),
          interactive: false,
          color: "22C55E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
        },
      },
      {
        type: "mini-calendar",
        name: "학사 캘린더",
        url: "/widget/mini-calendar?weekStart=mon&lang=ko&highlight=2563EB",
        editorUrl: "/create/mini-calendar",
        previewProps: {
          weekStart: "mon",
          lang: "ko",
          highlight: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "timeline",
        name: "시험 일정",
        url: "/widget/timeline?events=%EC%A4%91%EA%B0%84%EA%B3%A0%EC%82%AC~2026-04-20|%EA%B8%B0%EB%A7%90%EA%B3%A0%EC%82%AC~2026-06-25|%EC%88%98%EB%8A%A5~2026-11-19&color=E11D48",
        editorUrl: "/create/timeline",
        previewProps: {
          events: [
            { title: "중간고사", date: "2026-04-20" },
            { title: "기말고사", date: "2026-06-25" },
            { title: "수능", date: "2026-11-19" },
          ],
          color: "E11D48",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
  {
    id: "minimal",
    title: "미니멀 워크스페이스",
    desc: "깔끔한 노션 헤더를 위한 시계 + 날씨 + 명언 세트",
    layout: [[0, 1, 2], [3, 4]],
    widgets: [
      {
        type: "clock",
        name: "모노 시계",
        url: "/widget/clock?timezone=Asia/Seoul&format=24h&font=mono&color=1E1E1E&bg=FFFFFF",
        editorUrl: "/create/clock",
        previewProps: {
          timezone: "Asia/Seoul",
          format: "24h",
          font: "mono",
          color: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
          showSeconds: true,
          blink: true,
        },
      },
      {
        type: "weather",
        name: "서울 날씨",
        url: "/widget/weather?lat=37.5665&lon=126.978&city=%EC%84%9C%EC%9A%B8&unit=celsius",
        editorUrl: "/create/weather",
        previewProps: {
          city: "서울",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "quote",
        name: "명언 카드",
        url: "/widget/quote?text=%EC%98%A4%EB%8A%98%EC%9D%B4+%EA%B0%80%EC%9E%A5+%EC%A0%8A%EC%9D%80+%EB%82%A0%EC%9D%B4%EB%8B%A4&author=%EC%9E%91%EC%9E%90%EB%AF%B8%EC%83%81&font=serif",
        editorUrl: "/create/quote",
        previewProps: {
          text: "오늘이 가장 젊은 날이다",
          author: "작자미상",
          font: "serif",
          textColor: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "time-progress",
        name: "하루 진행률",
        url: "/widget/time-progress?type=day&color=2563EB",
        editorUrl: "/create/time-progress",
        previewProps: {
          type: "day",
          color: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "mini-calendar",
        name: "미니 캘린더",
        url: "/widget/mini-calendar?weekStart=mon&lang=ko&highlight=2563EB",
        editorUrl: "/create/mini-calendar",
        previewProps: {
          weekStart: "mon",
          lang: "ko",
          highlight: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
  {
    id: "reading",
    title: "독서 관리",
    desc: "읽기 목표 추적 + 독서 계획 타임라인으로 독서 습관 만들기",
    layout: [[5], [0, 1], [2, 4], [3]],
    widgets: [
      {
        type: "reading",
        name: "읽기 진행률",
        url: "/widget/reading?title=%ED%81%B4%EB%A6%B0+%EC%BD%94%EB%93%9C&current=180&total=300&color=2563EB",
        editorUrl: "/create/reading",
        previewProps: {
          title: "클린 코드",
          currentPage: 180,
          totalPages: 300,
          color: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "goal",
        name: "올해 독서 목표",
        url: "/widget/goal?title=%EC%98%AC%ED%95%B4+%EB%8F%85%EC%84%9C&current=8&target=24&unit=%EA%B6%8C&color=22C55E",
        editorUrl: "/create/goal",
        previewProps: {
          title: "올해 독서",
          current: 8,
          target: 24,
          unit: "권",
          color: "22C55E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "quote",
        name: "독서 명언",
        url: "/widget/quote?text=%EC%B1%85%EC%9D%80+%EB%8F%84%EB%81%BC%EB%82%A0+%EC%88%98+%EC%9E%88%EB%8A%94+%EA%BF%88%EC%9D%B4%EB%8B%A4&author=%EB%84%AC+%EA%B2%8C%EC%9D%B4%EB%A8%BC&font=serif",
        editorUrl: "/create/quote",
        previewProps: {
          text: "책은 도끼날 수 있는 꿈이다",
          author: "닐 게이먼",
          font: "serif",
          textColor: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "timeline",
        name: "독서 계획",
        url: "/widget/timeline?events=%ED%81%B4%EB%A6%B0+%EC%BD%94%EB%93%9C~2026-03-15|%EB%94%A5+%EC%9B%8C%ED%81%AC~2026-04-30|%EC%9B%90%EC%94%BD+%EC%96%B4%EB%A6%B0%EC%99%95%EC%9E%90~2026-06-15&color=6366F1",
        editorUrl: "/create/timeline",
        previewProps: {
          events: [
            { title: "클린 코드", date: "2026-03-15" },
            { title: "딥 워크", date: "2026-04-30" },
            { title: "원씽 어린왕자", date: "2026-06-15" },
          ],
          color: "6366F1",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "counter",
        name: "완독 카운터",
        url: "/widget/counter?label=%EC%99%84%EB%8F%85&initial=0&step=1&btnColor=6366F1",
        editorUrl: "/create/counter",
        previewProps: {
          label: "완독",
          initial: 0,
          step: 1,
          btnColor: "6366F1",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "banner",
        name: "독서 격려 배너",
        url: "/widget/banner?texts=%EC%98%A4%EB%8A%98%EB%8F%84+%ED%95%9C+%ED%8E%98%EC%9D%B4%EC%A7%80+%EB%8D%94+%F0%9F%93%96&anim=scroll&bold=true",
        editorUrl: "/create/banner",
        previewProps: {
          texts: ["오늘도 한 페이지 더 📖"],
          animation: "scroll",
          bold: true,
          color: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
  {
    id: "goals",
    title: "목표 & 습관",
    desc: "저축·운동 목표 달성률 + 습관 관리 + D-Day 카운트다운",
    layout: [[0, 1], [2, 3], [4, 5]],
    widgets: [
      {
        type: "goal",
        name: "저축 목표",
        url: "/widget/goal?title=%EC%A0%80%EC%B6%95&current=350000&target=1000000&unit=%EC%9B%90&style=bar&color=22C55E",
        editorUrl: "/create/goal",
        previewProps: {
          title: "저축",
          current: 350000,
          target: 1000000,
          unit: "원",
          style: "bar",
          color: "22C55E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "goal",
        name: "운동 목표",
        url: "/widget/goal?title=%EC%9A%B4%EB%8F%99&current=12&target=30&unit=%ED%9A%8C&style=ring&color=E11D48",
        editorUrl: "/create/goal",
        previewProps: {
          title: "운동",
          current: 12,
          target: 30,
          unit: "회",
          style: "ring",
          color: "E11D48",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "habit",
        name: "운동 습관 트래커",
        url: "/widget/habit?title=%EC%9A%B4%EB%8F%99&view=week&weekStart=mon&color=F59E0B",
        editorUrl: "/create/habit",
        previewProps: {
          title: "운동",
          view: "week",
          weekStart: "mon",
          checkedDates: new Set(["2026-02-23", "2026-02-25", "2026-02-27"]),
          interactive: false,
          color: "F59E0B",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
        },
      },
      {
        type: "dday",
        name: "목표 달성일",
        url: "/widget/dday?title=%EB%AA%A9%ED%91%9C+%EB%8B%AC%EC%84%B1%EC%9D%BC&date=2026-12-31&bg=7C3AED&text=FFFFFF",
        editorUrl: "/create/dday",
        previewProps: {
          title: "목표 달성일",
          targetDate: "2026-12-31",
          bgColor: "7C3AED",
          textColor: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "life-calendar",
        name: "인생 달력",
        url: "/widget/life-calendar?birthdate=2000-01-01&lifespan=80&color=7C3AED&shape=round",
        editorUrl: "/create/life-calendar",
        previewProps: {
          birthdate: "2000-01-01",
          lifespan: 80,
          color: "7C3AED",
          shape: "round",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "time-progress",
        name: "올해 진행률",
        url: "/widget/time-progress?type=year&color=2563EB",
        editorUrl: "/create/time-progress",
        previewProps: {
          type: "year",
          color: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
  {
    id: "aesthetic",
    title: "감성 꾸미기",
    desc: "노션 페이지를 예쁘게 꾸미는 장식용 위젯 모음",
    layout: [[0], [1, 3], [4], [2]],
    widgets: [
      {
        type: "banner",
        name: "텍스트 배너",
        url: "/widget/banner?texts=%EC%98%A4%EB%8A%98%EB%8F%84+%ED%99%94%EC%9D%B4%ED%8C%85!+%F0%9F%92%AA&anim=scroll&bold=true",
        editorUrl: "/create/banner",
        previewProps: {
          texts: ["오늘도 화이팅! 💪"],
          animation: "scroll",
          bold: true,
          color: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "music",
        name: "음악 플레이어",
        url: "/widget/music?title=Chill+Beats&artist=Lo-Fi+Radio&progress=45&artColor=6366F1",
        editorUrl: "/create/music",
        previewProps: {
          title: "Chill Beats",
          artist: "Lo-Fi Radio",
          progress: 45,
          artColor: "6366F1",
          color: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "bookmark",
        name: "북마크 카드",
        url: "/widget/bookmark?url=https://github.com&title=GitHub&desc=%EB%82%B4+%EA%B9%83%ED%97%88%EB%B8%8C+%ED%94%84%EB%A1%9C%ED%95%84&showIcon=true",
        editorUrl: "/create/bookmark",
        previewProps: {
          url: "https://github.com",
          title: "GitHub",
          desc: "내 깃허브 프로필",
          color: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
          linkable: false,
        },
      },
      {
        type: "analog-clock",
        name: "아날로그 시계",
        url: "/widget/analog-clock?timezone=Asia/Seoul&showNumbers=true&numStyle=quarter",
        editorUrl: "/create/analog-clock",
        previewProps: {
          timezone: "Asia/Seoul",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 16,
          fontSize: "md",
        },
      },
      {
        type: "quote",
        name: "감성 명언",
        url: "/widget/quote?text=%EA%BD%83%EC%9D%B4+%EC%A7%80%EA%B3%A0+%EB%82%98%EC%84%9C%EC%95%BC+%EB%B4%84%EC%9D%B8+%EC%A4%84+%EC%95%88%EB%8B%A4&author=%EC%9D%B4%ED%95%B4%EC%9D%B8&font=serif&italic=true",
        editorUrl: "/create/quote",
        previewProps: {
          text: "꽃이 지고 나서야 봄인 줄 안다",
          author: "이해인",
          font: "serif",
          textColor: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
  {
    id: "time-master",
    title: "시간 관리 마스터",
    desc: "시간 관련 위젯을 총집합한 생산성 대시보드",
    layout: [[0, 1], [2, 3], [4]],
    widgets: [
      {
        type: "clock",
        name: "디지털 시계",
        url: "/widget/clock?timezone=Asia/Seoul&format=24h&font=mono&color=1E1E1E&bg=FFFFFF",
        editorUrl: "/create/clock",
        previewProps: {
          timezone: "Asia/Seoul",
          format: "24h",
          font: "mono",
          color: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
          showSeconds: true,
          blink: true,
        },
      },
      {
        type: "analog-clock",
        name: "아날로그 시계",
        url: "/widget/analog-clock?timezone=Asia/Seoul&showNumbers=true&numStyle=all",
        editorUrl: "/create/analog-clock",
        previewProps: {
          timezone: "Asia/Seoul",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 16,
          fontSize: "md",
        },
      },
      {
        type: "stopwatch",
        name: "스톱워치",
        url: "/widget/stopwatch?showMs=true&showLap=true&btnColor=E11D48",
        editorUrl: "/create/stopwatch",
        previewProps: {
          showMs: true,
          showLap: true,
          btnColor: "E11D48",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "pomodoro",
        name: "뽀모도로 타이머",
        url: "/widget/pomodoro?work=25&break=5&color=2563EB&pStyle=ring",
        editorUrl: "/create/pomodoro",
        previewProps: {
          workTime: 25,
          breakTime: 5,
          color: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "time-progress",
        name: "하루 진행률",
        url: "/widget/time-progress?type=day&color=F59E0B&style=ring",
        editorUrl: "/create/time-progress",
        previewProps: {
          type: "day",
          color: "F59E0B",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
  {
    id: "daily",
    title: "데일리 대시보드",
    desc: "매일 체크하는 일상 관리 대시보드",
    layout: [[2, 0], [1, 3], [4]],
    widgets: [
      {
        type: "weather",
        name: "오늘 날씨",
        url: "/widget/weather?lat=37.5665&lon=126.978&city=%EC%84%9C%EC%9A%B8&unit=celsius",
        editorUrl: "/create/weather",
        previewProps: {
          city: "서울",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "mini-calendar",
        name: "이번 달 캘린더",
        url: "/widget/mini-calendar?weekStart=mon&lang=ko&highlight=2563EB",
        editorUrl: "/create/mini-calendar",
        previewProps: {
          weekStart: "mon",
          lang: "ko",
          highlight: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "clock",
        name: "현재 시각",
        url: "/widget/clock?timezone=Asia/Seoul&format=24h&font=mono&date=true&color=1E1E1E&bg=FFFFFF",
        editorUrl: "/create/clock",
        previewProps: {
          timezone: "Asia/Seoul",
          format: "24h",
          font: "mono",
          color: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
          showSeconds: true,
          blink: true,
          showDate: true,
        },
      },
      {
        type: "counter",
        name: "물 마시기",
        url: "/widget/counter?label=%EB%AC%BC+%EB%A7%88%EC%8B%9C%EA%B8%B0+(%EC%9E%94)&initial=0&step=1&btnColor=2563EB",
        editorUrl: "/create/counter",
        previewProps: {
          label: "물 마시기 (잔)",
          initial: 0,
          step: 1,
          btnColor: "2563EB",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "time-progress",
        name: "하루 진행률",
        url: "/widget/time-progress?type=day&color=22C55E",
        editorUrl: "/create/time-progress",
        previewProps: {
          type: "day",
          color: "22C55E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
  {
    id: "self-growth",
    title: "자기 성장 일지",
    desc: "인생 전체를 조망하는 자기계발 대시보드",
    layout: [[0], [1, 2], [3, 4]],
    widgets: [
      {
        type: "life-calendar",
        name: "인생 달력",
        url: "/widget/life-calendar?birthdate=2000-01-01&lifespan=80&color=22C55E&shape=round",
        editorUrl: "/create/life-calendar",
        previewProps: {
          birthdate: "2000-01-01",
          lifespan: 80,
          color: "22C55E",
          shape: "round",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "goal",
        name: "올해 목표",
        url: "/widget/goal?title=%EC%98%AC%ED%95%B4+%EB%AA%A9%ED%91%9C&current=25&target=100&unit=%25&style=ring&color=6366F1",
        editorUrl: "/create/goal",
        previewProps: {
          title: "올해 목표",
          current: 25,
          target: 100,
          unit: "%",
          style: "ring",
          color: "6366F1",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "habit",
        name: "자기계발 습관",
        url: "/widget/habit?title=%EC%9E%90%EA%B8%B0%EA%B3%84%EB%B0%9C&view=week&weekStart=mon&color=F59E0B",
        editorUrl: "/create/habit",
        previewProps: {
          title: "자기계발",
          view: "week",
          weekStart: "mon",
          checkedDates: new Set(["2026-02-23", "2026-02-24", "2026-02-26", "2026-02-27"]),
          interactive: false,
          color: "F59E0B",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
        },
      },
      {
        type: "dday",
        name: "목표 달성일",
        url: "/widget/dday?title=%EB%AA%A9%ED%91%9C+%EB%8B%AC%EC%84%B1%EC%9D%BC&date=2026-12-31&bg=1E1E1E&text=FFFFFF",
        editorUrl: "/create/dday",
        previewProps: {
          title: "목표 달성일",
          targetDate: "2026-12-31",
          bgColor: "1E1E1E",
          textColor: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
      {
        type: "quote",
        name: "동기부여 명언",
        url: "/widget/quote?text=%EC%9E%91%EC%9D%80+%EC%A7%84%EC%A0%84%EC%9D%B4+%ED%81%B0+%EB%B3%80%ED%99%94%EB%A5%BC+%EB%A7%8C%EB%93%A0%EB%8B%A4&author=%EC%A0%9C%EC%9E%84%EC%8A%A4+%ED%81%B4%EB%A6%AC%EC%96%B4&font=serif",
        editorUrl: "/create/quote",
        previewProps: {
          text: "작은 진전이 큰 변화를 만든다",
          author: "제임스 클리어",
          font: "serif",
          textColor: "1E1E1E",
          bg: "FFFFFF",
          borderRadius: 16,
          padding: 24,
          fontSize: "md",
        },
      },
    ],
  },
];
