export interface WidgetMeta {
  name: string;
  desc: string;
}

export const widgetMetadata: Record<string, WidgetMeta> = {
  "dday": { name: "D-Day 위젯", desc: "목표일까지 남은 일수를 표시하는 노션 위젯" },
  "clock": { name: "미니멀 시계", desc: "미니멀한 타이포그래피 시계 노션 위젯" },
  "analog-clock": { name: "아날로그 시계", desc: "클래식한 아날로그 시계 노션 위젯" },
  "mini-calendar": { name: "미니 캘린더", desc: "깔끔한 월간 캘린더 노션 위젯" },
  "timeline": { name: "타임라인", desc: "여러 일정을 타임라인으로 나열하는 노션 위젯" },
  "flip-clock": { name: "플립 시계", desc: "레트로 스플릿 플랩 스타일 시계 노션 위젯" },
  "time-progress": { name: "시간 진행률 바", desc: "오늘·이번 달·올해의 진행률을 표시하는 노션 위젯" },
  "life-calendar": { name: "인생 달력", desc: "기대수명을 주 단위로 시각화하는 노션 위젯" },
  "reading": { name: "읽기 진행률", desc: "책 읽기 목표 진행률을 표시하는 노션 위젯" },
  "goal": { name: "목표 진행률", desc: "자유 단위의 목표 진행률을 표시하는 노션 위젯" },
  "pomodoro": { name: "뽀모도로 타이머", desc: "집중·휴식을 번갈아 관리하는 타이머 노션 위젯" },
  "stopwatch": { name: "스톱워치", desc: "경과 시간을 측정하는 스톱워치 노션 위젯" },
  "counter": { name: "카운터", desc: "숫자를 세고 기록하는 카운터 노션 위젯" },
  "habit": { name: "습관 트래커", desc: "주간·월간 습관 체크를 관리하는 노션 위젯" },
  "qr-code": { name: "QR 코드", desc: "URL이나 텍스트를 QR 코드로 생성하는 노션 위젯" },
  "dice": { name: "주사위", desc: "주사위·동전·랜덤 뽑기 도구 노션 위젯" },
  "quote": { name: "명언 카드", desc: "감성 명언 텍스트 카드 노션 위젯" },
  "banner": { name: "텍스트 배너", desc: "애니메이션 텍스트 배너 노션 위젯" },
  "bookmark": { name: "북마크", desc: "링크 카드를 만들어 표시하는 노션 위젯" },
  "music": { name: "음악 플레이어", desc: "장식용 음악 플레이어 카드 노션 위젯" },
  "weather": { name: "날씨", desc: "현재 날씨와 예보를 표시하는 노션 위젯" },
  "moon-phase": { name: "달 위상", desc: "현재 달 모양과 조도를 표시하는 노션 위젯" },
  "sticky-note": { name: "메모지", desc: "포스트잇 스타일 메모 카드 노션 위젯" },
  "gradient": { name: "그라데이션", desc: "CSS 그라데이션 배너/구분선 노션 위젯" },
  "typewriter": { name: "타이핑 효과", desc: "텍스트가 타이핑되는 애니메이션 노션 위젯" },
  "todo": { name: "투두리스트", desc: "할 일 체크리스트를 관리하는 노션 위젯" },
  "github-contribution": { name: "GitHub 잔디", desc: "GitHub 기여 잔디 히트맵을 표시하는 노션 위젯" },
  "profile-card": { name: "프로필 카드", desc: "이름, 소개, SNS 링크가 포함된 명함 카드 노션 위젯" },
  "link-tree": { name: "링크 트리", desc: "여러 링크를 세로로 나열한 버튼 목록 노션 위젯" },
  "breathing": { name: "호흡 타이머", desc: "명상·호흡 가이드 타이머 노션 위젯" },
  "world-clock": { name: "세계 시계", desc: "여러 타임존을 한눈에 비교하는 노션 위젯" },
  "countdown": { name: "카운트다운", desc: "분·초 단위 카운트다운 타이머 노션 위젯" },
  "stats-card": { name: "통계 카드", desc: "KPI·통계 숫자를 표시하는 노션 위젯" },
  "color-palette": { name: "컬러 팔레트", desc: "컬러 스워치 팔레트를 표시하는 노션 위젯" },
  "divider": { name: "구분선", desc: "장식 구분선을 만드는 노션 위젯" },
  "timetable": { name: "시간표", desc: "주간 시간표를 표시하는 노션 위젯" },
  "flashcard": { name: "플래시카드", desc: "앞·뒤 카드로 암기를 도와주는 노션 위젯" },
  "water-tracker": { name: "물 마시기", desc: "일일 물 섭취량을 트래킹하는 노션 위젯" },
  "image-card": { name: "이미지 카드", desc: "외부 이미지를 캡션과 함께 표시하는 노션 위젯" },
  "currency": { name: "환율", desc: "실시간 환율 정보를 표시하는 노션 위젯" },
  "age-calculator": { name: "나이 계산기", desc: "생년월일 기반 정확한 나이를 실시간 표시하는 노션 위젯" },
  "radar-chart": { name: "레이더 차트", desc: "스킬·능력치를 거미줄 차트로 시각화하는 노션 위젯" },
  "pie-chart": { name: "도넛 차트", desc: "도넛/파이 차트로 비율을 시각화하는 노션 위젯" },
  "stepper": { name: "단계 진행", desc: "프로젝트 단계별 진행 상태를 표시하는 노션 위젯" },
  "battery": { name: "배터리", desc: "배터리 모양의 진행률을 표시하는 노션 위젯" },
  "testimonial": { name: "후기 카드", desc: "리뷰·추천사 카드를 만드는 노션 위젯" },
  "emoji-rain": { name: "이모지 비", desc: "이모지가 떨어지는 장식 애니메이션 노션 위젯" },
  "changelog": { name: "변경 로그", desc: "버전별 변경 이력을 표시하는 노션 위젯" },
  "matrix": { name: "매트릭스", desc: "아이젠하워 2×2 우선순위 매트릭스 노션 위젯" },
  "multi-progress": { name: "멀티 프로그레스", desc: "여러 항목의 진행률을 비교하는 노션 위젯" },
};
