import type { WidgetType } from "./widget-type";

export interface WidgetDefault {
  type: WidgetType;
  name: string;
  defaultUrl: string;
}

export const widgetDefaults: WidgetDefault[] = [
  { type: "dday", name: "D-Day 위젯", defaultUrl: "/widget/dday?title=D-Day&date=2026-12-31&bg=1E1E1E&text=FFFFFF" },
  { type: "clock", name: "미니멀 시계", defaultUrl: "/widget/clock?timezone=Asia/Seoul&format=24h&font=mono" },
  { type: "analog-clock", name: "아날로그 시계", defaultUrl: "/widget/analog-clock?timezone=Asia/Seoul" },
  { type: "mini-calendar", name: "미니 캘린더", defaultUrl: "/widget/mini-calendar?weekStart=mon&lang=ko" },
  { type: "timeline", name: "타임라인", defaultUrl: "/widget/timeline?events=일정1~2026-06-01|일정2~2026-09-01&color=2563EB" },
  { type: "time-progress", name: "시간 진행률 바", defaultUrl: "/widget/time-progress?type=year&color=2563EB" },
  { type: "life-calendar", name: "인생 달력", defaultUrl: "/widget/life-calendar?birthdate=2000-01-01&lifespan=80&color=22C55E" },
  { type: "reading", name: "읽기 진행률", defaultUrl: "/widget/reading?title=책+제목&current=50&total=300&color=2563EB" },
  { type: "goal", name: "목표 진행률", defaultUrl: "/widget/goal?title=목표&current=30&target=100&color=22C55E" },
  { type: "pomodoro", name: "뽀모도로 타이머", defaultUrl: "/widget/pomodoro?work=25&break=5&color=E11D48" },
  { type: "stopwatch", name: "스톱워치", defaultUrl: "/widget/stopwatch?btnColor=2563EB" },
  { type: "counter", name: "카운터", defaultUrl: "/widget/counter?label=카운터&initial=0&step=1&btnColor=2563EB" },
  { type: "habit", name: "습관 트래커", defaultUrl: "/widget/habit?title=습관&view=week&color=22C55E" },
  { type: "quote", name: "명언 카드", defaultUrl: "/widget/quote?text=오늘도+화이팅&author=작자미상&font=serif" },
  { type: "banner", name: "텍스트 배너", defaultUrl: "/widget/banner?texts=텍스트를+입력하세요&bold=true" },
  { type: "bookmark", name: "북마크", defaultUrl: "/widget/bookmark?url=https://example.com&title=북마크&desc=설명" },
  { type: "music", name: "음악 플레이어", defaultUrl: "/widget/music?title=Song&artist=Artist&artColor=6366F1" },
  { type: "weather", name: "날씨", defaultUrl: "/widget/weather?lat=37.5665&lon=126.978&city=서울" },
  { type: "gradient", name: "그라데이션", defaultUrl: "/widget/gradient?colors=6366F1|EC4899" },
  { type: "sticky-note", name: "메모지", defaultUrl: "/widget/sticky-note?text=메모를+입력하세요" },
  { type: "flip-clock", name: "플립 시계", defaultUrl: "/widget/flip-clock?timezone=Asia/Seoul" },
  { type: "moon-phase", name: "달 위상", defaultUrl: "/widget/moon-phase" },
  { type: "dice", name: "주사위", defaultUrl: "/widget/dice?color=2563EB" },
  { type: "qr-code", name: "QR 코드", defaultUrl: "/widget/qr-code?data=https://example.com" },
  { type: "typewriter", name: "타이핑 효과", defaultUrl: "/widget/typewriter?texts=%ED%83%80%EC%9D%B4%ED%95%91+%ED%9A%A8%EA%B3%BC+%EC%9C%84%EC%A0%AF" },
  { type: "github-contribution", name: "GitHub 잔디", defaultUrl: "/widget/github-contribution?color=22C55E" },
  { type: "profile-card", name: "프로필 카드", defaultUrl: "/widget/profile-card?name=홍길동&bio=Hello" },
  { type: "link-tree", name: "링크 트리", defaultUrl: "/widget/link-tree?title=내+링크" },
  { type: "breathing", name: "호흡 타이머", defaultUrl: "/widget/breathing" },
  { type: "world-clock", name: "세계 시계", defaultUrl: "/widget/world-clock" },
  { type: "countdown", name: "카운트다운 타이머", defaultUrl: "/widget/countdown?min=5" },
  { type: "stats-card", name: "통계 카드", defaultUrl: "/widget/stats-card" },
  { type: "color-palette", name: "컬러 팔레트", defaultUrl: "/widget/color-palette" },
  { type: "divider", name: "구분선", defaultUrl: "/widget/divider" },
  { type: "timetable", name: "시간표", defaultUrl: "/widget/timetable" },
  { type: "flashcard", name: "플래시카드", defaultUrl: "/widget/flashcard" },
  { type: "water-tracker", name: "물 마시기 트래커", defaultUrl: "/widget/water-tracker" },
  { type: "image-card", name: "이미지 카드", defaultUrl: "/widget/image-card" },
  { type: "currency", name: "환율", defaultUrl: "/widget/currency" },
  { type: "age-calculator", name: "나이 계산기", defaultUrl: "/widget/age-calculator?birthdate=1995-01-01" },
  { type: "radar-chart", name: "레이더 차트", defaultUrl: "/widget/radar-chart" },
  { type: "pie-chart", name: "도넛 차트", defaultUrl: "/widget/pie-chart" },
  { type: "stepper", name: "단계 진행", defaultUrl: "/widget/stepper" },
  { type: "battery", name: "배터리", defaultUrl: "/widget/battery?level=75" },
  { type: "testimonial", name: "후기 카드", defaultUrl: "/widget/testimonial" },
  { type: "emoji-rain", name: "이모지 비", defaultUrl: "/widget/emoji-rain" },
  { type: "changelog", name: "변경 로그", defaultUrl: "/widget/changelog" },
  { type: "matrix", name: "매트릭스", defaultUrl: "/widget/matrix" },
  { type: "multi-progress", name: "멀티 프로그레스", defaultUrl: "/widget/multi-progress" },
  { type: "fortune-cookie", name: "포춘 쿠키", defaultUrl: "/widget/fortune-cookie" },
  { type: "badge", name: "뱃지", defaultUrl: "/api/badge?label=상태&value=활성&color=22C55E" },
  { type: "group", name: "위젯 그룹", defaultUrl: "/widget/group" },
  { type: "anniversary", name: "기념일 카운터", defaultUrl: "/widget/anniversary?title=우리의+기념일&date=2024-03-14&color=E11D48" },
  { type: "season-countdown", name: "시즌 카운트다운", defaultUrl: "/widget/season-countdown?color=2563EB" },
  { type: "dual-clock", name: "듀얼 시계", defaultUrl: "/widget/dual-clock?tz1=Asia/Seoul&tz2=America/New_York" },
  { type: "gpa-calculator", name: "학점 계산기", defaultUrl: "/widget/gpa-calculator?current=3.8&max=4.5&color=6366F1" },
  { type: "savings-goal", name: "저축 목표", defaultUrl: "/widget/savings-goal?title=여행+자금&current=500000&target=2000000&color=22C55E" },
  { type: "book-goal", name: "독서 목표", defaultUrl: "/widget/book-goal?current=8&target=24&color=F59E0B" },
  { type: "kanban", name: "칸반 보드", defaultUrl: "/widget/kanban?color=6366F1" },
  { type: "routine-timer", name: "루틴 타이머", defaultUrl: "/widget/routine-timer?steps=스트레칭~5|명상~10|독서~20&color=2563EB" },
  { type: "memo-board", name: "메모 보드", defaultUrl: "/widget/memo-board?noteColor=FBBF24" },
  { type: "password-gen", name: "비밀번호 생성기", defaultUrl: "/widget/password-gen?length=16&color=2563EB" },
  { type: "social-counter", name: "소셜 카운터", defaultUrl: "/widget/social-counter?items=YouTube~1200|Instagram~850&color=E11D48" },
  { type: "guestbook", name: "방명록", defaultUrl: "/widget/guestbook?title=방명록&color=6366F1" },
  { type: "poll", name: "투표", defaultUrl: "/widget/poll?question=좋아하는+계절은?&options=봄|여름|가을|겨울&color=2563EB" },
  { type: "vocabulary", name: "단어장", defaultUrl: "/widget/vocabulary?color=7C3AED" },
  { type: "mini-gallery", name: "미니 갤러리", defaultUrl: "/widget/mini-gallery?interval=5" },
  { type: "ascii-art", name: "아스키 아트", defaultUrl: "/widget/ascii-art?text=HELLO&color=22C55E" },
  { type: "noise-bg", name: "노이즈 배경", defaultUrl: "/widget/noise-bg?type=gradient-flow&color1=6366F1&color2=EC4899" },
  { type: "daily-color", name: "오늘의 색", defaultUrl: "/widget/daily-color?showHex=true&showName=true" },
  { type: "countup", name: "카운트업", defaultUrl: "/widget/countup?title=경과+시간&date=2024-01-01&color=2563EB" },
  { type: "mini-map", name: "미니 지도", defaultUrl: "/widget/mini-map?lat=37.5665&lon=126.978&zoom=13&label=서울" },
  { type: "rating-card", name: "별점 카드", defaultUrl: "/widget/rating-card?title=영화+리뷰&rating=4.5&color=F59E0B" },
];
