export type WidgetType =
  | "dday" | "life-calendar" | "time-progress" | "clock" | "quote"
  | "pomodoro" | "mini-calendar" | "analog-clock" | "counter" | "weather"
  | "reading" | "habit" | "timeline" | "banner"
  | "bookmark" | "goal" | "stopwatch" | "music"
  | "gradient" | "sticky-note" | "flip-clock" | "moon-phase" | "dice" | "qr-code"
  | "typewriter"
  | "todo"
  | "github-contribution"
  | "profile-card"
  | "link-tree"
  | "breathing"
  | "world-clock"
  | "countdown"
  | "stats-card"
  | "color-palette"
  | "divider"
  | "timetable"
  | "flashcard"
  | "water-tracker"
  | "image-card"
  | "currency"
  | "age-calculator"
  | "radar-chart"
  | "pie-chart"
  | "stepper"
  | "battery"
  | "testimonial"
  | "emoji-rain"
  | "changelog"
  | "matrix"
  | "multi-progress"
  | "badge"
  | "fortune-cookie"
  | "group"
  | "anniversary"
  | "season-countdown"
  | "dual-clock"
  | "gpa-calculator"
  | "savings-goal"
  | "book-goal"
  | "kanban"
  | "routine-timer"
  | "memo-board"
  | "password-gen"
  | "social-counter"
  | "guestbook"
  | "poll"
  | "vocabulary"
  | "mini-gallery"
  | "ascii-art"
  | "noise-bg"
  | "daily-color"
  | "countup"
  | "mini-map"
  | "rating-card";
