export type WidgetType =
  | "dday" | "life-calendar" | "time-progress" | "clock" | "quote"
  | "pomodoro" | "mini-calendar" | "analog-clock" | "counter" | "weather"
  | "reading" | "habit" | "timeline" | "banner"
  | "bookmark" | "goal" | "stopwatch" | "music"
  | "gradient" | "sticky-note" | "flip-clock" | "moon-phase" | "dice" | "qr-code"
  | "typewriter"
  | "todo"
  | "github-contribution"
  | "profile-card"
  | "link-tree"
  | "breathing"
  | "world-clock"
  | "countdown"
  | "stats-card"
  | "color-palette"
  | "divider"
  | "timetable"
  | "flashcard"
  | "water-tracker"
  | "image-card"
  | "currency"
  | "age-calculator"
  | "radar-chart"
  | "pie-chart"
  | "stepper"
  | "battery"
  | "testimonial"
  | "emoji-rain"
  | "changelog"
  | "matrix"
  | "multi-progress"
  | "badge"
  | "fortune-cookie"
  | "group";
